# Generated by Django 4.2.3 on 2023-08-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('released', models.BooleanField(default=False)),
            ],
        ),
    ]
