# Generated by Django 4.2.3 on 2023-08-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='MusicItem',
        ),
    ]
