# Generated by Django 4.2.3 on 2023-08-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_rename_music_musicitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('tour_date', models.DateField()),
                ('tickets', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='musicitem',
            old_name='Title',
            new_name='title',
        ),
    ]
